[mongodb]
mongodb.sunilreddyc.site
[catalogue]
catalogue.sunilreddyc.site
[redis]
redis.sunilreddyc.site
[user]
user.sunilreddyc.site
[cart]
cart.sunilreddyc.site
[frontend]
frontend.sunilreddyc.site
[mysql]
mysql.sunilreddyc.site
[shipping]
shipping.sunilreddyc.site
[rabbitmq]
rabbitmq.sunilreddyc.site
[payment]
payment.sunilreddyc.site
